AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ParamPrimaryAccountId:
    Type: String
    Description: The Account ID of the Master account, used to grant cross-account role assumption.
  ParamReadOnlyRoleName:
    Type: String
    Description: The name to give the ReadOnly role.

Resources:

  ReadOnly:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: [!Ref ParamPrimaryAccountId]
            Action: ['sts:AssumeRole']
      MaxSessionDuration: 43200 # 12 hours (in seconds)
      RoleName: !Ref ParamReadOnlyRoleName

  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub '${ParamReadOnlyRoleName}-policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'access-analyzer:Get*'
              - 'access-analyzer:Describe*'
              - 'access-analyzer:List*'
              - 'acm:Get*'
              - 'acm:Describe*'
              - 'acm:List*'
              - 'acm-pca:Get*'
              - 'acm-pca:Describe*'
              - 'acm-pca:List*'
              - 'apigateway:Get*'
              - 'apigateway:Describe*'
              - 'apigateway:List*'
              - 'application-autoscaling:Get*'
              - 'application-autoscaling:Describe*'
              - 'application-autoscaling:List*'
              - 'appsync:Get*'
              - 'appsync:Describe*'
              - 'appsync:List*'
              - 'artifact:Get*'
              - 'artifact:Describe*'
              - 'artifact:List*'
              - 'autoscaling:Get*'
              - 'autoscaling:Describe*'
              - 'autoscaling:List*'
              - 'autoscaling-plans:Get*'
              - 'autoscaling-plans:Describe*'
              - 'autoscaling-plans:List*'
              - 'backup:Get*'
              - 'backup:Describe*'
              - 'backup:List*'
              - 'backup-storage:Get*'
              - 'backup-storage:Describe*'
              - 'backup-storage:List*'
              - 'batch:Get*'
              - 'batch:Describe*'
              - 'batch:List*'
              - 'budgets:Get*'
              - 'budgets:Describe*'
              - 'budgets:List*'
              - 'ce:Get*'
              - 'ce:Describe*'
              - 'ce:List*'
              - 'chatbot:Get*'
              - 'chatbot:Describe*'
              - 'chatbot:List*'
              - 'cloud9:Get*'
              - 'cloud9:Describe*'
              - 'cloud9:List*'
              - 'clouddirectory:Get*'
              - 'clouddirectory:Describe*'
              - 'clouddirectory:List*'
              - 'cloudformation:Get*'
              - 'cloudformation:Describe*'
              - 'cloudformation:List*'
              - 'cloudfront:Get*'
              - 'cloudfront:Describe*'
              - 'cloudfront:List*'
              - 'cloudtrail:Get*'
              - 'cloudtrail:Describe*'
              - 'cloudtrail:List*'
              - 'cloudwatch:Get*'
              - 'cloudwatch:Describe*'
              - 'cloudwatch:List*'
              - 'codebuild:Get*'
              - 'codebuild:Describe*'
              - 'codebuild:List*'
              - 'codecommit:Get*'
              - 'codecommit:Describe*'
              - 'codecommit:List*'
              - 'codedeploy:Get*'
              - 'codedeploy:Describe*'
              - 'codedeploy:List*'
              - 'codepipeline:Get*'
              - 'codepipeline:Describe*'
              - 'codepipeline:List*'
              - 'codestar:Get*'
              - 'codestar:Describe*'
              - 'codestar:List*'
              - 'codestar-notifications:Get*'
              - 'codestar-notifications:Describe*'
              - 'codestar-notifications:List*'
              - 'cognito-identity:Get*'
              - 'cognito-identity:Describe*'
              - 'cognito-identity:List*'
              - 'cognito-idp:Get*'
              - 'cognito-idp:Describe*'
              - 'cognito-idp:List*'
              - 'cognito-sync:Get*'
              - 'cognito-sync:Describe*'
              - 'cognito-sync:List*'
              - 'comprehend:Get*'
              - 'comprehend:Describe*'
              - 'comprehend:List*'
              - 'compute-optimizer:Get*'
              - 'compute-optimizer:Describe*'
              - 'compute-optimizer:List*'
              - 'config:Get*'
              - 'config:Describe*'
              - 'config:List*'
              - 'cur:Get*'
              - 'cur:Describe*'
              - 'cur:List*'
              - 'datapipeline:Get*'
              - 'datapipeline:Describe*'
              - 'datapipeline:List*'
              - 'datasync:Get*'
              - 'datasync:Describe*'
              - 'datasync:List*'
              - 'dax:Get*'
              - 'dax:Describe*'
              - 'dax:List*'
              - 'dbqms:Get*'
              - 'dbqms:Describe*'
              - 'dbqms:List*'
              - 'detective:Get*'
              - 'detective:Describe*'
              - 'detective:List*'
              - 'devicefarm:Get*'
              - 'devicefarm:Describe*'
              - 'devicefarm:List*'
              - 'discovery:Get*'
              - 'discovery:Describe*'
              - 'discovery:List*'
              - 'dlm:Get*'
              - 'dlm:Describe*'
              - 'dlm:List*'
              - 'dms:Get*'
              - 'dms:Describe*'
              - 'dms:List*'
              - 'ds:Get*'
              - 'ds:Describe*'
              - 'ds:List*'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:Describe*'
              - 'dynamodb:Get*'
              - 'dynamodb:List*'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'ebs:Describe*'
              - 'ebs:Get*'
              - 'ebs:List*'
              - 'ec2:Get*'
              - 'ec2:Describe*'
              - 'ec2:List*'
              - 'ecr:Get*'
              - 'ecr:Describe*'
              - 'ecr:List*'
              - 'ecs:Get*'
              - 'ecs:Describe*'
              - 'ecs:List*'
              - 'elasticache:Get*'
              - 'elasticache:Describe*'
              - 'elasticache:List*'
              - 'elasticfilesystem:Get*'
              - 'elasticfilesystem:Describe*'
              - 'elasticfilesystem:List*'
              - 'elasticloadbalancing:Get*'
              - 'elasticloadbalancing:Describe*'
              - 'elasticloadbalancing:List*'
              - 'es:Get*'
              - 'es:Describe*'
              - 'es:List*'
              - 'events:Get*'
              - 'events:Describe*'
              - 'events:List*'
              - 'execute-api:Get*'
              - 'execute-api:Describe*'
              - 'execute-api:List*'
              - 'fms:Get*'
              - 'fms:Describe*'
              - 'fms:List*'
              - 'forecast:Get*'
              - 'forecast:Describe*'
              - 'forecast:List*'
              - 'glacier:Get*'
              - 'glacier:Describe*'
              - 'glacier:List*'
              - 'globalaccelerator:Get*'
              - 'globalaccelerator:Describe*'
              - 'globalaccelerator:List*'
              - 'glue:Get*'
              - 'glue:Describe*'
              - 'glue:List*'
              - 'guardduty:Get*'
              - 'guardduty:Describe*'
              - 'guardduty:List*'
              - 'health:Get*'
              - 'health:Describe*'
              - 'health:List*'
              - 'iam:Get*'
              - 'iam:Describe*'
              - 'iam:List*'
              - 'imagebuilder:Get*'
              - 'imagebuilder:Describe*'
              - 'imagebuilder:List*'
              - 'importexport:Get*'
              - 'importexport:Describe*'
              - 'importexport:List*'
              - 'inspector:Get*'
              - 'inspector:Describe*'
              - 'inspector:List*'
              - 'iq:Get*'
              - 'iq:Describe*'
              - 'iq:List*'
              - 'iq-permission:Get*'
              - 'iq-permission:Describe*'
              - 'iq-permission:List*'
              - 'kafka:Get*'
              - 'kafka:Describe*'
              - 'kafka:List*'
              - 'kinesis:Get*'
              - 'kinesis:Describe*'
              - 'kinesis:List*'
              - 'kinesisanalytics:Get*'
              - 'kinesisanalytics:Describe*'
              - 'kinesisanalytics:List*'
              - 'kms:Get*'
              - 'kms:Describe*'
              - 'kms:List*'
              - 'lakeformation:Get*'
              - 'lakeformation:Describe*'
              - 'lakeformation:List*'
              - 'lambda:Get*'
              - 'lambda:Describe*'
              - 'lambda:List*'
              - 'license-manager:Get*'
              - 'license-manager:Describe*'
              - 'license-manager:List*'
              - 'logs:Get*'
              - 'logs:Describe*'
              - 'logs:List*'
              - 'machinelearning:Get*'
              - 'machinelearning:Describe*'
              - 'machinelearning:List*'
              - 'macie:Get*'
              - 'macie:Describe*'
              - 'macie:List*'
              - 'mgh:Get*'
              - 'mgh:Describe*'
              - 'mgh:List*'
              - 'mobileanalytics:Get*'
              - 'mobileanalytics:Describe*'
              - 'mobileanalytics:List*'
              - 'mobilehub:Get*'
              - 'mobilehub:Describe*'
              - 'mobilehub:List*'
              - 'mobiletargeting:Get*'
              - 'mobiletargeting:Describe*'
              - 'mobiletargeting:List*'
              - 'mq:Get*'
              - 'mq:Describe*'
              - 'mq:List*'
              - 'networkmanager:Get*'
              - 'networkmanager:Describe*'
              - 'networkmanager:List*'
              - 'organizations:Get*'
              - 'organizations:Describe*'
              - 'organizations:List*'
              - 'pi:Get*'
              - 'pi:Describe*'
              - 'pi:List*'
              - 'polly:Get*'
              - 'polly:Describe*'
              - 'polly:List*'
              - 'pricing:Get*'
              - 'pricing:Describe*'
              - 'pricing:List*'
              - 'qldb:Get*'
              - 'qldb:Describe*'
              - 'qldb:List*'
              - 'quicksight:Get*'
              - 'quicksight:Describe*'
              - 'quicksight:List*'
              - 'ram:Get*'
              - 'ram:Describe*'
              - 'ram:List*'
              - 'rds:Get*'
              - 'rds:Describe*'
              - 'rds:List*'
              - 'rds-data:Get*'
              - 'rds-data:Describe*'
              - 'rds-data:List*'
              - 'rds-db:Get*'
              - 'rds-db:Describe*'
              - 'rds-db:List*'
              - 'rekognition:Get*'
              - 'rekognition:Describe*'
              - 'rekognition:List*'
              - 'resource-groups:Get*'
              - 'resource-groups:Describe*'
              - 'resource-groups:List*'
              - 'route53:Get*'
              - 'route53:Describe*'
              - 'route53:List*'
              - 'route53domains:Get*'
              - 'route53domains:Describe*'
              - 'route53domains:List*'
              - 'route53resolver:Get*'
              - 'route53resolver:Describe*'
              - 'route53resolver:List*'
              - 's3:Get*'
              - 's3:Describe*'
              - 's3:List*'
              - 'savingsplans:Get*'
              - 'savingsplans:Describe*'
              - 'savingsplans:List*'
              - 'schemas:Get*'
              - 'schemas:Describe*'
              - 'schemas:List*'
              - 'secretsmanager:Get*'
              - 'secretsmanager:Describe*'
              - 'secretsmanager:List*'
              - 'securityhub:Get*'
              - 'securityhub:Describe*'
              - 'securityhub:List*'
              - 'serverlessrepo:Get*'
              - 'serverlessrepo:Describe*'
              - 'serverlessrepo:List*'
              - 'servicecatalog:Get*'
              - 'servicecatalog:Describe*'
              - 'servicecatalog:List*'
              - 'servicediscovery:Get*'
              - 'servicediscovery:Describe*'
              - 'servicediscovery:List*'
              - 'servicequotas:Get*'
              - 'servicequotas:Describe*'
              - 'servicequotas:List*'
              - 'ses:Get*'
              - 'ses:Describe*'
              - 'ses:List*'
              - 'shield:Get*'
              - 'shield:Describe*'
              - 'shield:List*'
              - 'sns:Get*'
              - 'sns:Describe*'
              - 'sns:List*'
              - 'sqs:Get*'
              - 'sqs:Describe*'
              - 'sqs:List*'
              - 'ssm:Get*'
              - 'ssm:Describe*'
              - 'ssm:List*'
              - 'ssmmessages:Get*'
              - 'ssmmessages:Describe*'
              - 'ssmmessages:List*'
              - 'sso:Get*'
              - 'sso:Describe*'
              - 'sso:List*'
              - 'sso-directory:Get*'
              - 'sso-directory:Describe*'
              - 'sso-directory:List*'
              - 'states:Get*'
              - 'states:Describe*'
              - 'states:List*'
              - 'storagegateway:Get*'
              - 'storagegateway:Describe*'
              - 'storagegateway:List*'
              - 'sts:Get*'
              - 'sts:Describe*'
              - 'sts:List*'
              - 'support:Get*'
              - 'support:Describe*'
              - 'support:List*'
              - 'swf:Get*'
              - 'swf:Describe*'
              - 'swf:List*'
              - 'tag:Get*'
              - 'tag:Describe*'
              - 'tag:List*'
              - 'textract:Get*'
              - 'textract:Describe*'
              - 'textract:List*'
              - 'transcribe:Get*'
              - 'transcribe:Describe*'
              - 'transcribe:List*'
              - 'transfer:Get*'
              - 'transfer:Describe*'
              - 'transfer:List*'
              - 'translate:Get*'
              - 'translate:Describe*'
              - 'translate:List*'
              - 'trustedadvisor:Get*'
              - 'trustedadvisor:Describe*'
              - 'trustedadvisor:List*'
              - 'waf:Get*'
              - 'waf:Describe*'
              - 'waf:List*'
              - 'waf-regional:Get*'
              - 'waf-regional:Describe*'
              - 'waf-regional:List*'
              - 'wam:Get*'
              - 'wam:Describe*'
              - 'wam:List*'
              - 'wellarchitected:Get*'
              - 'wellarchitected:Describe*'
              - 'wellarchitected:List*'
              - 'workspaces:Get*'
              - 'workspaces:Describe*'
              - 'workspaces:List*'
              - 'xray:Get*'
              - 'xray:Describe*'
              - 'xray:List*'
            Resource: ['*']
      Roles:
        - !Ref ReadOnly

Outputs:
  ReadOnlyArn:
    Description: ReadOnly Arn
    Value: !GetAtt ReadOnly.Arn
  ReadOnlyRoleId:
    Description: ReadOnly RoleId
    Value: !GetAtt ReadOnly.RoleId
